version: 0.2
phases:
  pre_build:
    commands:
      # - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USER} --password-stdin
      - echo ${ECR_ID} | docker login --username AWS --password-stdin public.ecr.aws/${ECR_ID}
  build:
    commands:
      # - docker build -t my-angular-app:latest .
      - docker build -t hung_angular_docker .
  post_build:
    commands:
      # - docker tag my-angular-app:latest ${DOCKERHUB_USER}/my-angular-app:latest
      # - docker push ${DOCKERHUB_USER}/my-angular-app:latest
      - docker tag hung_angular_docker:latest public.ecr.aws/${ECR_ID}/hung_angular_docker:latest
      - docker push public.ecr.aws/${ECR_ID}/hung_angular_docker:latest
